export const SET_ERROR = 'SET_ERROR';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CONTACTS_LIST = 'SET_CONTACTS_LIST';
export const ADD_CONTACT_TO_LIST = 'ADD_CONTACT_TO_LIST';
export const UPDATE_CONTACT_IN_LIST = 'UPDATE_CONTACT_IN_LIST';
export const DELETE_CONTACT_FROM_LIST = 'DELETE_CONTACT_FROM_LIST';

export const GET_CONTACTS_LIST = 'GET_CONTACTS_LIST';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
